foo: this is from github
name: dongsheng

# * 配置服务的路劲规则：
# *
# * /{application}/{profile}[/{label}]
# * /{application}-{profile}.yml
# * /{label}/{application}-{profile}.yml
# * /{application}-{profile}.properties
# * /{label}/{application}-{profile}.properties
